controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

diff_cont:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.28
    wheel_radius: 0.035
    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    use_stamped_vel: false
    velocity_rolling_window_size: 10
